version: '3.8'
services:
  dsi_service:
    build: .
    container_name: dsi_service
    ports:
      - "${PORT:-4003}:${PORT:-4003}"
    env_file:
      - .env
    restart: unless-stopped
    shm_size: '1gb' # Importante para Puppeteer para evitar cuelgues de Chromium
