name: Deploy DSI Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: 🤖 Deploy DSI Service
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Clonar repositorio
        uses: actions/checkout@v4

      - name: 📤 Enviar archivos por SSH (SCP)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "."
          target: "${{ secrets.PROJECT_PATH }}"
          rm: false

      - name: 🔄 Levantar / Re-construir Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            docker compose up -d --build
